Week 4
pesto-students/team-mohit-kamal-gurudattpuranik25 pull request #7
Opened 2023-06-22 16:25 UTC by gurudattpuranik25

Kindly review week-4 assignment and provide the comments

2023-06-24 01:09 UTC, kamalmohit commented on Week-4/Async_JS/Custom_Promise/script.js
> +  thenu(onFulfilled, onRejected) {
Typo here @gurudattpuranik25

2023-06-24 01:12 UTC, kamalmohit requested changes
Please resolve the comments @gurudattpuranik25

2023-06-24 04:22 UTC, gurudattpuranik25 commented
Typo fixed and PR is raised, please check

2023-06-25 19:20 UTC, kamalmohit approved these changes

2023-06-26 05:33 UTC, merged